apiVersion: apps/v1beta2 
kind: Deployment
metadata:
  name: nodeapp
  labels:
    app: nodeapp
spec:
  selector:
    matchLabels:
      app: nodeapp
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
      - image: node:slim
        name: nodeapp
        ports:
        - containerPort: 3000
          name: nodeapp
